(function () {
'use strict';

var app = angular.module('myFirstApp', ['ngFlag']);
app.controller('FantasyLeagueController', function ($scope) {
	$scope.leagueTotal =[{ "Group_Name": "ImGROOT", "Group_Total": 3777 }, 
{ "Group_Name": "S3D", "Group_Total": 3743 }, 
{ "Group_Name": "Ethical Bookies", "Group_Total": 3620 }, 
{ "Group_Name": "Juice Joint", "Group_Total": 3587 }, 
{ "Group_Name": "Brahmachary 4", "Group_Total": 3499 }, 
{ "Group_Name": "HadoopRocks", "Group_Total": 3499 }, 
{ "Group_Name": "MAHA - XI", "Group_Total": 3428 }, 
{ "Group_Name": "Hullad Gang", "Group_Total": 3324 }, 
{ "Group_Name": "Rockstars", "Group_Total": 3265 }, 
{ "Group_Name": "Money Matters", "Group_Total": 3253 }, 
{ "Group_Name": "Crazy 4", "Group_Total": 3105 }, 
{ "Group_Name": "Preangles", "Group_Total": 3102 }, 
{ "Group_Name": "SWAG", "Group_Total": 2985 }, 
{ "Group_Name": "Jaya 4", "Group_Total": 2958 }, 
{ "Group_Name": "Atlanta", "Group_Total": 2842 }, 
{ "Group_Name": " WARRIORS_007", "Group_Total": 2702 }, 
{ "Group_Name": "Skeleton Army", "Group_Total": 2370 }, 
{ "Group_Name": "WingsXI", "Group_Total": 2284 }, 
{ "Group_Name": "Avengers", "Group_Total": 2241 }
];


	
	$scope.tournament=[
{ "type": "Feature", "properties": { "Team_Name": " All stars XI", "Manager": " pramuz", "Group_Name": "NA", "Match1": 0, "Match2": 0, "Match3": 261, "Match4": 148, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 409 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Bala", "Manager": " Bala Divvela", "Group_Name": "NA", "Match1": 257, "Match2": 0, "Match3": 0, "Match4": 363, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 620 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " DMWinner", "Manager": " Rajiv", "Group_Name": "NA", "Match1": 0, "Match2": 0, "Match3": 58, "Match4": 138, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 196 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " HadoopRocks", "Manager": " JJ", "Group_Name": "NA", "Match1": 579, "Match2": 0, "Match3": 125, "Match4": 150, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 854 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Mahajan", "Manager": " Mahajan", "Group_Name": "Crazy 4", "Match1": 0, "Match2": 0, "Match3": 103, "Match4": 488, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 591 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " ManiXI", "Manager": " Manish Bajpai", "Group_Name": "NA", "Match1": 744, "Match2": 0, "Match3": 348, "Match4": 0, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1092 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " SomIndia", "Manager": " Somnath Maddi", "Group_Name": "NA", "Match1": 0, "Match2": 0, "Match3": 263, "Match4": 359, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 622 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " THUNDERBIRD", "Manager": " PRIYANKA", "Group_Name": "NA", "Match1": 0, "Match2": 0, "Match3": 214, "Match4": 122, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 336 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Abhinav's - XI", "Manager": " Abhinav", "Group_Name": "MAHA - XI", "Match1": 464, "Match2": 0, "Match3": 133, "Match4": 296, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 893 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Absolut`s 11", "Manager": " Aman Jain", "Group_Name": "Juice Joint", "Match1": 214, "Match2": 0, "Match3": 213, "Match4": 424, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 851 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Ajay11", "Manager": " Ajay Sudrik", "Group_Name": "NA", "Match1": 48, "Match2": 0, "Match3": 0, "Match4": 50, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 98 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Akash11", "Manager": " Akash Morey", "Group_Name": "NA", "Match1": 460, "Match2": 0, "Match3": 237, "Match4": 94, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 791 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Animesh XI", "Manager": " Animesh Saxena", "Group_Name": "Ethical Bookies", "Match1": 283, "Match2": 0, "Match3": 482, "Match4": 291, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1056 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " ARS XI", "Manager": " ARS", "Group_Name": "NA", "Match1": 555, "Match2": 0, "Match3": 80, "Match4": 467, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1102 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Atlanta 10", "Manager": " amit gupta", "Group_Name": "Atlanta", "Match1": 366, "Match2": 0, "Match3": 0, "Match4": 382, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 748 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Atlanta 17", "Manager": " Bhautik09", "Group_Name": "Atlanta", "Match1": 411, "Match2": 0, "Match3": 109, "Match4": 251, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 771 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Atlanta 40", "Manager": " Garvit", "Group_Name": "Atlanta", "Match1": 44, "Match2": 0, "Match3": 171, "Match4": 279, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 494 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Atlanta 9", "Manager": " shashi", "Group_Name": "Atlanta", "Match1": 594, "Match2": 0, "Match3": 0, "Match4": 235, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 829 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Avengers", "Manager": " wolverine", "Group_Name": "Avengers", "Match1": 297, "Match2": 0, "Match3": 29, "Match4": 212, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 538 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " bahubali-11", "Manager": " Baliram Munde", "Group_Name": "NA", "Match1": 36, "Match2": 0, "Match3": 60, "Match4": -7, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 89 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " BoOsTerS-!!", "Manager": " Dewakar Prasad", "Group_Name": "NA", "Match1": 203, "Match2": 0, "Match3": 140, "Match4": 401, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 744 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Buck", "Manager": " Ravi Rana", "Group_Name": "Skeleton Army", "Match1": 58, "Match2": 0, "Match3": 511, "Match4": 25, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 594 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " champions", "Manager": " vishakha sadawarte", "Group_Name": "ImGROOT", "Match1": 719, "Match2": 0, "Match3": 157, "Match4": 356, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1232 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Chits_XI", "Manager": " Chetan CC", "Group_Name": "NA", "Match1": 471, "Match2": 0, "Match3": 35, "Match4": 225, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 731 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Crazy11", "Manager": " Sandeep Bibekar", "Group_Name": "Preangles", "Match1": 286, "Match2": 0, "Match3": 58, "Match4": 307, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 651 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Crazy4cric", "Manager": " Crazy4Cric", "Group_Name": "WingsXI", "Match1": 0, "Match2": 0, "Match3": 285, "Match4": 348, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 633 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " cric-dudes", "Manager": " cric-dude", "Group_Name": "SWAG", "Match1": 15, "Match2": 0, "Match3": 160, "Match4": 127, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 302 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " CricFan", "Manager": " aj12009_3", "Group_Name": "WingsXI", "Match1": 455, "Match2": 0, "Match3": 66, "Match4": 0, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 521 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " D44", "Manager": " Santosh J", "Group_Name": "NA", "Match1": 544, "Match2": 0, "Match3": 0, "Match4": 168, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 712 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Durgesh11", "Manager": " Durgesh Nema", "Group_Name": "NA", "Match1": 351, "Match2": 0, "Match3": 1, "Match4": 25, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 377 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " EagleBlasters11", "Manager": " KrishnaKant", "Group_Name": "WingsXI", "Match1": 207, "Match2": 0, "Match3": 458, "Match4": 0, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 665 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " EnemyOfBall", "Manager": " KOLLA XI", "Group_Name": "WingsXI", "Match1": 0, "Match2": 0, "Match3": 0, "Match4": 465, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 465 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " fabXI", "Manager": " brandon", "Group_Name": "NA", "Match1": 149, "Match2": 0, "Match3": 435, "Match4": 379, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 963 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Faceless_XI", "Manager": " Harsh Singhal", "Group_Name": "NA", "Match1": 529, "Match2": 0, "Match3": 291, "Match4": 280, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1100 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Fallen Angles", "Manager": " Parag Saxena", "Group_Name": "Skeleton Army", "Match1": 66, "Match2": 0, "Match3": 75, "Match4": 328, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 469 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " GaHir", "Manager": " Gahir", "Group_Name": "Avengers", "Match1": 213, "Match2": 0, "Match3": 77, "Match4": 0, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 290 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " GeetRockers", "Manager": " Geet.Bhalshankar", "Group_Name": "ImGROOT", "Match1": 605, "Match2": 0, "Match3": 135, "Match4": 224, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 964 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Gully XI", "Manager": " Praveen", "Group_Name": "Jaya 4", "Match1": 155, "Match2": 0, "Match3": 288, "Match4": 357, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 800 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " HadoopRocks", "Manager": " Akash Shelke-Patil", "Group_Name": " HadoopRocks", "Match1": 509, "Match2": 0, "Match3": 167, "Match4": 317, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 993 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " HadoopRocks", "Manager": " Arjun More", "Group_Name": " HadoopRocks", "Match1": 380, "Match2": 0, "Match3": 297, "Match4": 387, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1064 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " HadoopRocks", "Manager": " Deven Chauhan", "Group_Name": " HadoopRocks", "Match1": 341, "Match2": 0, "Match3": 46, "Match4": 208, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 595 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " HadoopRocks", "Manager": " Chennuri Gouri Shankar", "Group_Name": " HadoopRocks", "Match1": 210, "Match2": 0, "Match3": 154, "Match4": 0, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 364 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " HK-11", "Manager": " HKishor", "Group_Name": "NA", "Match1": 39, "Match2": 0, "Match3": 0, "Match4": 248, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 287 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " INDIA", "Manager": " Devesh Tripathi", "Group_Name": "S3D", "Match1": 635, "Match2": 0, "Match3": 167, "Match4": 389, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1191 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " INDIA", "Manager": " Pranjal", "Group_Name": "Ethical Bookies", "Match1": 276, "Match2": 0, "Match3": 116, "Match4": 327, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 719 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " indian", "Manager": " Nagesh Biradar", "Group_Name": "NA", "Match1": 108, "Match2": 0, "Match3": 140, "Match4": 498, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 746 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Interstellar XI", "Manager": " Sagar11", "Group_Name": "NA", "Match1": 428, "Match2": 0, "Match3": 103, "Match4": 229, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 760 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " ironman", "Manager": " Vikram", "Group_Name": "Jaya 4", "Match1": 430, "Match2": 0, "Match3": 125, "Match4": 363, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 918 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " JaCk DaNIeL$", "Manager": " SumitRoy", "Group_Name": "Juice Joint", "Match1": 454, "Match2": 0, "Match3": 341, "Match4": 225, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1020 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Jhajhria_XI", "Manager": "Suniel Jhajhria", "Group_Name": "Crazy 4", "Match1": 136, "Match2": 0, "Match3": 328, "Match4": 63, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 527 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Kitkity", "Manager": " Kitkitti", "Group_Name": "Crazy 4", "Match1": 247, "Match2": 0, "Match3": 77, "Match4": 263, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 587 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Kush11", "Manager": " pradeep kushwaha", "Group_Name": "WARRIORS_007", "Match1": 411, "Match2": 0, "Match3": 58, "Match4": 86, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 555 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Mad_Avengers", "Manager": " Shweta", "Group_Name": "ImGROOT", "Match1": 724, "Match2": 0, "Match3": 23, "Match4": 0, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 747 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Manasee@Fantacy", "Manager": " Manasee", "Group_Name": "NA", "Match1": 15, "Match2": 0, "Match3": 103, "Match4": 131, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 249 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " ManglaM", "Manager": " ManglaM", "Group_Name": "Avengers", "Match1": 489, "Match2": 0, "Match3": 89, "Match4": 257, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 835 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " minions", "Manager": " HP", "Group_Name": "ImGROOT", "Match1": 286, "Match2": 0, "Match3": 31, "Match4": 517, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 834 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Money Matters", "Manager": " Anurupa", "Group_Name": " Money Matters", "Match1": 441, "Match2": 0, "Match3": 17, "Match4": 498, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 956 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " money matters", "Manager": " ANIL", "Group_Name": " Money Matters", "Match1": 261, "Match2": 0, "Match3": 397, "Match4": 122, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 780 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Moneymatters", "Manager": " Ami", "Group_Name": " Money Matters", "Match1": 599, "Match2": 0, "Match3": 79, "Match4": 158, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 836 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " multiple scoregasm", "Manager": " bunty", "Group_Name": "SWAG", "Match1": 584, "Match2": 0, "Match3": 379, "Match4": 389, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1352 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " neha XI", "Manager": " Neha", "Group_Name": "Hullad Gang", "Match1": 252, "Match2": 0, "Match3": 232, "Match4": 252, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 736 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " nidhiXI", "Manager": " nidhi rawat", "Group_Name": "Rockstars", "Match1": 639, "Match2": 0, "Match3": 179, "Match4": 267, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1085 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Nikita's XI", "Manager": " Nikita", "Group_Name": " Money Matters", "Match1": 464, "Match2": 0, "Match3": 0, "Match4": 0, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 464 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " nimish", "Manager": " nimish choudhary", "Group_Name": "NA", "Match1": 300, "Match2": 0, "Match3": 29, "Match4": 43, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 372 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Oceans11", "Manager": " Pradnya", "Group_Name": "NA", "Match1": 549, "Match2": 0, "Match3": 148, "Match4": 220, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 917 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Old Monk 11", "Manager": " Anish", "Group_Name": "Juice Joint", "Match1": 339, "Match2": 0, "Match3": 305, "Match4": 331, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 975 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Omi`sXI", "Manager": " Omi", "Group_Name": "Rockstars", "Match1": 204, "Match2": 0, "Match3": 0, "Match4": 382, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 586 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Optimus Prime", "Manager": " Optimus Prime", "Group_Name": "Jaya 4", "Match1": 0, "Match2": 0, "Match3": 268, "Match4": 324, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 592 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Paati", "Manager": " Nikhil Patidar", "Group_Name": "Ethical Bookies", "Match1": 171, "Match2": 0, "Match3": 341, "Match4": 216, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 728 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " paroolXI", "Manager": " parool singh", "Group_Name": "Rockstars", "Match1": 305, "Match2": 0, "Match3": 195, "Match4": 142, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 642 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " POKEMON", "Manager": " Poonam Mishra", "Group_Name": "Hullad Gang", "Match1": 452, "Match2": 0, "Match3": 349, "Match4": 58, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 859 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Prasad's Team", "Manager": " Prasad Kulkarni", "Group_Name": "NA", "Match1": 183, "Match2": 0, "Match3": 23, "Match4": 272, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 478 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " PSX1", "Manager": " Param", "Group_Name": "Preangles", "Match1": 599, "Match2": 0, "Match3": 328, "Match4": 275, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1202 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Reddy's XI", "Manager": " Ashoka Reddy", "Group_Name": "MAHA - XI", "Match1": 187, "Match2": 0, "Match3": 197, "Match4": 263, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 647 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " RMFantasy_143", "Manager": " Mahendranadh Dasari", "Group_Name": "MAHA - XI", "Match1": 156, "Match2": 0, "Match3": 382, "Match4": 267, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 805 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " RO@rInG RheOS", "Manager": " Hemanth Reddy", "Group_Name": "MAHA - XI", "Match1": 257, "Match2": 0, "Match3": 405, "Match4": 421, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1083 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Rochwanis", "Manager": " Akshay Rochwani", "Group_Name": "Hullad Gang", "Match1": 315, "Match2": 0, "Match3": 222, "Match4": 327, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 864 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Roshan_11", "Manager": " Roshan", "Group_Name": "NA", "Match1": 291, "Match2": 0, "Match3": 23, "Match4": 8, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 322 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Royal Alen's XI", "Manager": " Alen", "Group_Name": "Crazy 4", "Match1": 603, "Match2": 0, "Match3": 425, "Match4": 372, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1400 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Sabko Batting Milegi", "Manager": " Akshay Gujar", "Group_Name": "Brahmachary 4", "Match1": 351, "Match2": 0, "Match3": 50, "Match4": 387, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 788 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " sachinb", "Manager": " Sachin Bijwar", "Group_Name": "S3D", "Match1": 480, "Match2": 0, "Match3": 296, "Match4": 245, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1021 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " sachinDM", "Manager": " sachin", "Group_Name": "NA", "Match1": 39, "Match2": 0, "Match3": 369, "Match4": 109, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 517 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Savan", "Manager": " Savan", "Group_Name": "S3D", "Match1": 495, "Match2": 0, "Match3": 214, "Match4": 313, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1022 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Scorpio11", "Manager": " Sushauvik Deb", "Group_Name": "S3D", "Match1": 233, "Match2": 0, "Match3": 169, "Match4": 107, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 509 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " sdnaphs11", "Manager": " Sanjay Naphade", "Group_Name": "NA", "Match1": 399, "Match2": 0, "Match3": 396, "Match4": 267, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1062 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Shadow assassins", "Manager": " theMudit05", "Group_Name": "Skeleton Army", "Match1": 311, "Match2": 0, "Match3": 154, "Match4": 206, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 671 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Sky", "Manager": " Nihar Kininge", "Group_Name": "Ethical Bookies", "Match1": 471, "Match2": 0, "Match3": 120, "Match4": 54, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 645 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Spartans X1", "Manager": " Dhiren", "Group_Name": "Preangles", "Match1": 310, "Match2": 0, "Match3": 0, "Match4": 324, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 634 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " StrangeRiders", "Manager": " Saurabh Padhy", "Group_Name": "Avengers", "Match1": 315, "Match2": 0, "Match3": 24, "Match4": 239, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 578 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " super 11", "Manager": " Suryaprakash Veeravalli", "Group_Name": "NA", "Match1": 0, "Match2": 0, "Match3": 137, "Match4": 135, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 272 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Swag", "Manager": " Swag", "Group_Name": "SWAG", "Match1": 354, "Match2": 0, "Match3": 29, "Match4": 368, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 751 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Swap", "Manager": " Swap", "Group_Name": "SWAG", "Match1": 223, "Match2": 0, "Match3": 233, "Match4": 124, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 580 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " T_Boyzz", "Manager": " Tushar Bhutte", "Group_Name": "Brahmachary 4", "Match1": 494, "Match2": 0, "Match3": 488, "Match4": 271, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1253 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Team XI", "Manager": " Ganesh Renuke", "Group_Name": "NA", "Match1": 137, "Match2": 0, "Match3": 32, "Match4": 25, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 194 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Team_Challangers", "Manager": " Abhijeet", "Group_Name": "NA", "Match1": 291, "Match2": 0, "Match3": 156, "Match4": 307, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 754 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Team_Sandip", "Manager": " Sandip Brahmachary", "Group_Name": "Brahmachary 4", "Match1": 100, "Match2": 0, "Match3": 200, "Match4": 350, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 650 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Team11", "Manager": " Ankit Mittal", "Group_Name": "NA", "Match1": 504, "Match2": 0, "Match3": 242, "Match4": 362, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 1108 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " TeamDevil", "Manager": " TeamIndia", "Group_Name": "NA", "Match1": 628, "Match2": 0, "Match3": 160, "Match4": 187, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 975 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " teamName", "Manager": " displayName", "Group_Name": "NA", "Match1": 599, "Match2": 0, "Match3": 0, "Match4": 299, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 898 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Valkyrie", "Manager": " Pooja", "Group_Name": "Rockstars", "Match1": 474, "Match2": 0, "Match3": 96, "Match4": 382, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 952 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " Warriors", "Manager": " Aditi", "Group_Name": "Hullad Gang", "Match1": 113, "Match2": 0, "Match3": 527, "Match4": 225, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 865 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " WARRIORS_007", "Manager": " Shashank Kulkarni", "Group_Name": "WARRIORS_007", "Match1": 520, "Match2": 0, "Match3": 29, "Match4": 282, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 831 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " WARRIORS_007", "Manager": " ASHISH", "Group_Name": "WARRIORS_007", "Match1": 367, "Match2": 0, "Match3": 74, "Match4": 225, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 666 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " WARRIORS_007", "Manager": " Prashant", "Group_Name": "WARRIORS_007", "Match1": 114, "Match2": 0, "Match3": 74, "Match4": 118, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 306 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " WorldChampions", "Manager": " Ram", "Group_Name": "Brahmachary 4", "Match1": 121, "Match2": 0, "Match3": 277, "Match4": 410, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 808 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " xman", "Manager": " Amruta", "Group_Name": "Jaya 4", "Match1": 39, "Match2": 0, "Match3": 295, "Match4": 314, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 648 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " YourKiller", "Manager": " Jasvinder Singh", "Group_Name": "Skeleton Army", "Match1": 137, "Match2": 0, "Match3": 319, "Match4": 180, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 636 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": " zingaro11", "Manager": " Mayur", "Group_Name": "Juice Joint", "Match1": 159, "Match2": 0, "Match3": 269, "Match4": 313, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 741 }, "geometry": null },
{ "type": "Feature", "properties": { "Team_Name": "Amit'XI", "Manager": " Amit's XI", "Group_Name": "Preangles", "Match1": 281, "Match2": 0, "Match3": 77, "Match4": 257, "Match5": null, "Match6": null, "Match7": null, "Match8": null, "Match9": null, "Match10": null, "Match11": null, "Match12": null, "Match13": null, "Match14": null, "Match15": null, "Total": 615 }, "geometry": null }
]



;


    
    $scope.sort = {
        column: '',
        descending: false
    };    
    
    $scope.changeSorting = function(column) {

        var sort = $scope.sort;

        if (sort.column == column) {
            sort.descending = !sort.descending;
        } else {
            sort.column = column;
            sort.descending = false;
        }
    };
    $scope.selectedUserImage="images/ravi.jpg";
    $scope.selectedCls = function(column) {
        return column == $scope.sort.column && 'sort-' + $scope.sort.descending;
    };
});

})();
